### ISSUE TITLE
Flatpak version of motrix is not working

### ISSUE THREAD

**Issue by SpamixOfficial** [agalwood/Motrix#1387]
**Describe the bug**
The bug makes the motrix app unusable. The bug basically doesnt create a window for the app, and when you try to get a window and it finally pops up, it's all white.

**To Reproduce**
1. Start motrix through flatpak

**Expected behavior**
What happens is that the app creates a background process, but no actual GUI, then quits.

**Environment (please complete the following information):**
 - OS & Version: [EndeavourOS Cassini Neo]
 - Motrix Version: [1.6.11 (the latest on flatpak)]
 - Installation package type: [Flatpak]

**Additional context**
**Terminal ouput**
```
19:54:12.556 › [Motrix] Logger init
19:54:12.559 › [Motrix] Logger init
19:54:12.815 › [Motrix] openedAtLogin: false
Gtk-Message: 19:54:12.818: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:54:12.818: Failed to load module "canberra-gtk-module"
19:54:12.885 › [Motrix] UPnPManager port mapping:  21301
19:54:12.886 › [Motrix] UPnPManager port mapping:  26701
19:54:12.886 › [Motrix] Engie pid path: /home/alexander/.var/app/net.agalwood.Motrix/config/Motrix/engine.pid
extraConfig===> {
  'all-proxy': '',
  'allow-overwrite': false,
  'auto-file-renaming': true,
  'bt-exclude-tracker': '',
  'bt-load-saved-metadata': true,
  'bt-save-metadata': true,
  'bt-tracker': 'udp://93.158.213.92:1337/announce,udp://151.80.120.113:2810/announce,udp://45.154.253.6:6969/announce,http://45.154.253.6:80/announce,udp://193.42.111.57:9337/announce,udp://156.234.201.18:80/announce,udp://91.216.110.53:451/announce,udp://211.75.29.254:6969/announce,udp://185.230.4.150:1337/announce,udp://23.137.251.45:6969/announce,udp://185.181.60.155:80/announce,udp://185.44.82.25:1337/announce,udp://149.202.88.193:80/announce,udp://184.105.151.166:6969/announce,udp://208.83.20.20:6969/announce,udp://207.241.226.111:6969/announce,udp://89.36.216.8:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://9.rarbg.com:2810/announce,udp://tracker.openbittorrent.com:6969/announce,udp://opentracker.i2p.rocks:6969/announce,https://opentracker.i2p.rocks:443/announce,http://tracker.openbittorrent.com:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.dler.org:6969/announce,udp://p4p.arenabg.com:1337/announce,udp://open.stealth.si:80/announce,udp://open.demonii.com:1337/announce,udp://ipv4.tracker.harry.lu:80/announce,udp://explodie.org:6969/announce,udp://exodus.desync.com:6969/announce,https://tracker.lilithraws.org:443/announce,https://tr.burnabyhighstar.com:443/announce,http://tracker.mywaifu.best:6969/announce,udp://zecircle.xyz:6969/announce',
  continue: true,
  'dht-file-path': '/home/alexander/.var/app/net.agalwood.Motrix/config/Motrix/dht.dat',
  'dht-file-path6': '/home/alexander/.var/app/net.agalwood.Motrix/config/Motrix/dht6.dat',
  'dht-listen-port': 26701,
  dir: '/home/alexander/Downloads',
  'listen-port': 21301,
  'max-concurrent-downloads': 5,
  'max-connection-per-server': 64,
  'max-download-limit': 0,
  'max-overall-download-limit': 0,
  'max-overall-upload-limit': '256K',
  'min-split-size': '1M',
  'no-proxy': '',
  pause: true,
  'rpc-listen-port': 16800,
  'rpc-secret': '',
  'seed-ratio': 1,
  'seed-time': 60,
  split: 64,
  'user-agent': 'Transmission/2.94'
}
19:54:12.894 › [Motrix] main engine client connect { host: '127.0.0.1', port: 16800, secret: '' }
19:54:12.933 › [Motrix] auto sync tracker checkIsNeedRun: false
19:54:14.688 › [Motrix] UPnPManager map 21301 failed, error:  Error: UPnP port mapping failed
    at /app/motrix/resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /app/motrix/resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at /app/motrix/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/app/motrix/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
19:54:14.689 › [Motrix] UPnPManager map 26701 failed, error:  Error: UPnP port mapping failed
    at /app/motrix/resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /app/motrix/resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at /app/motrix/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/app/motrix/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[3:0221/195415.213090:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
/app/bin/start-motrix: line 3:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/motrix/motrix "$@"

**Comment by bohanubis** [comment]
does this work now

**Comment by agalwood** [comment]
Closing as legacy-v1.

Motrix v2 has replaced the legacy 1.x codebase, so this issue is no longer tracked. If it still reproduces with the latest Motrix v2 beta, please open a new issue with the current Motrix version, OS, reproduction steps, and logs.

Motrix v2 已替换 1.x 旧架构，因此不再跟踪此 issue。若问题仍能在最新 Motrix v2 beta 复现，请重新提交 issue，并附上当前版本、系统、复现步骤和日志。
