### ISSUE TITLE
求助 npm run build时报错

### ISSUE THREAD

**Issue by Badbadboy827** [agalwood/Motrix#278]
在官网上下载的node ;npm版本6.9.0，用的树莓派3B+设备报了下面的错误，是依赖不支持arm7l么，有什么办法解决么

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/builder-effective-config.yaml
Error: Unsupported arch arm
    at archFromString (/home/pi/Motrix/node_modules/builder-util/src/arch.ts:43:13)
    at computeArchToTargetNamesMap (/home/pi/Motrix/node_modules/app-builder-lib/src/targets/targetFactory.ts:30:24)
    at /home/pi/Motrix/node_modules/app-builder-lib/src/packager.ts:415:41
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/home/pi/Motrix/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/pi/Motrix/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/pi/Motrix/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/pi/Motrix/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/home/pi/Motrix/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/pi/Motrix/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/home/pi/Motrix/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/pi/Motrix/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/pi/Motrix/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/home/pi/Motrix/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Motrix@1.3.8 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Motrix@1.3.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-21T10_08_01_490Z-debug.log

**Comment by agalwood** [comment]
我没折腾过，你树莓派装的什么系统？arm 的编译你要不参考下 electron-builder 的文档：
https://www.electron.build/api/electron-builder#electron-builderarch-enum

**Comment by weearc** [comment]
node版本有点旧呀…另外用rpi构建electron应用可能有点问题，至少构建脚本你可能需要改下。
个人构建环境是Arch Linux x86_64，nodejs 11.x，yarn nightly。还不你试试看在虚拟机里构建？

**Comment by agalwood** [comment]
@weearc 他说的是 npm 版本，6.9.0 不算旧的
@Badbadboy827 arm 的构建你可以请教下 @weearc 哈哈哈

**Comment by Badbadboy827** [comment]
好的，我安装的树莓派官方debain系统

**Comment by agalwood** [comment]
Closing as legacy-v1.

Motrix v2 has replaced the legacy 1.x codebase, so this issue is no longer tracked. If it still reproduces with the latest Motrix v2 beta, please open a new issue with the current Motrix version, OS, reproduction steps, and logs.

Motrix v2 已替换 1.x 旧架构，因此不再跟踪此 issue。若问题仍能在最新 Motrix v2 beta 复现，请重新提交 issue，并附上当前版本、系统、复现步骤和日志。
