### ISSUE TITLE
突然不能用，点击关于页面发现引擎版本号为空，查看任务管理器没有ari2c的进程

### ISSUE THREAD

**Issue by TTTPOB** [agalwood/Motrix#414]
**错误描述**
今天开机突然不能用，chrome设置好的rpc也不能调用，点击关于页面发现引擎版本号为空，查看任务管理器没有ari2c的进程。但是翻看安装文件夹ari2c.exe存在

**如何重现**
重现步骤，如：
开机（

**预期的行为**
预期行为是能用

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

![image](https://user-images.githubusercontent.com/19909103/64470195-eda47b00-d171-11e9-80f2-91e30d4c885f.png)

**运行环境**
 - 操作系统类型： Windows 10
 - 具体版本：  18362.267
 - Motrix 版本： 1.4.1
 - 安装包类型：exe, installer

**更多信息**
我在期间并没有做过更新等操作。但是今天测试覆盖重装发现不行。

**Comment by TTTPOB** [comment]
另外尝试卸载重装也出现同样问题。我安装时选择的是仅为我安装

**Comment by TTTPOB** [comment]
尝试单文件绿色版无效

**Comment by TTTPOB** [comment]
zip绿色版无效

**Comment by TTTPOB** [comment]
[2019-06-06 01:47:25.893] [warn] [Motrix] Logger init
[2019-06-06 01:47:59.265] [warn] [Motrix] Logger init
[2019-06-06 01:48:07.246] [warn] [Motrix] Logger init
[2019-06-07 12:48:34.420] [warn] [Motrix] Logger init
[2019-06-07 12:49:09.980] [warn] [Motrix] Logger init
[2019-06-08 16:25:01.608] [warn] [Motrix] Logger init
[2019-06-08 16:25:34.363] [warn] [Motrix] Logger init
[2019-06-08 16:36:03.787] [warn] [Motrix] Logger init
[2019-06-08 16:36:34.438] [warn] [Motrix] Logger init
[2019-06-08 17:43:42.914] [warn] [Motrix] Logger init
[2019-06-08 18:31:14.323] [warn] [Motrix] Logger init
[2019-06-08 19:38:45.840] [warn] [Motrix] Logger init
[2019-06-10 02:31:47.426] [warn] [Motrix] Logger init
[2019-06-10 23:04:52.473] [warn] [Motrix] Logger init
[2019-06-11 02:23:57.646] [warn] [Motrix] Logger init
[2019-06-12 15:03:52.153] [warn] [Motrix] Logger init
[2019-06-12 21:44:47.310] [warn] [Motrix] Logger init
[2019-06-12 21:44:47.530] [warn] second-instance====> { preventDefault: [Function: preventDefault],
  sender:
   App {
     _events:
      { login: [Function],
        'certificate-error': [Function],
        'select-client-certificate': [Function],
        quit: [Function],
        'web-contents-created': [Array],
        'session-created': [Function],
        'will-quit': [Array],
        ready: [Function],
        'second-instance': [Function],
        'open-url': [Function],
        activate: [Function],
        'before-quit': [Function],
        'window-all-closed': [Function] },
     _eventsCount: 13,
     _maxListeners: undefined,
     setApplicationMenu: [Function: setApplicationMenu],
     getApplicationMenu: [Function: getApplicationMenu],
     commandLine:
      { appendSwitch: [Function: appendSwitch],
        appendArgument: [Function: appendArgument] },
     getAppMetrics: [Function],
     isPackaged: true,
     allowNTLMCredentialsForAllDomains: [Function] } } [ 'C:\\Tools\\Programs\\download\\motrix\\Motrix.exe' ] C:\Tools\Programs\download\motrix
[2019-06-12 22:43:21.110] [warn] [Motrix] Logger init
[2019-06-13 18:23:18.774] [warn] [Motrix] Logger init
[2019-06-20 19:04:09.031] [warn] [Motrix] Logger init
[2019-06-20 20:43:12.773] [warn] [Motrix] Logger init
[2019-06-21 18:04:58.631] [warn] [Motrix] Logger init
[2019-06-24 13:09:55.521] [warn] [Motrix] Logger init
[2019-06-24 14:56:38.089] [warn] [Motrix] Logger init
[2019-06-26 00:10:16.990] [warn] [Motrix] Logger init
[2019-06-26 00:20:39.205] [warn] [Motrix] Logger init
[2019-06-26 21:54:54.077] [warn] [Motrix] Logger init
[2019-07-09 08:46:58.960] [warn] [Motrix] Logger init
[2019-07-09 09:24:14.609] [warn] [Motrix] Logger init
[2019-07-12 10:42:27.515] [warn] [Motrix] Logger init
[2019-07-19 09:08:07.326] [warn] [Motrix] Logger init
[2019-07-22 19:25:52.288] [warn] [Motrix] Logger init
[2019-07-24 18:51:12.065] [warn] [Motrix] Logger init
[2019-07-24 18:51:20.065] [warn] [Motrix] Logger init
[2019-07-24 18:52:58.963] [warn] [Motrix] Logger init
[2019-07-24 18:52:59.207] [warn] openedAtLogin===> false
[2019-07-24 18:56:54.335] [warn] [Motrix] Logger init
[2019-07-24 18:56:54.554] [warn] openedAtLogin===> false
[2019-07-24 18:57:14.616] [warn] [Motrix] Logger init
[2019-07-24 18:57:14.839] [warn] openedAtLogin===> false
[2019-07-25 09:16:04.120] [warn] [Motrix] Logger init
[2019-07-25 09:16:04.341] [warn] openedAtLogin===> true
[2019-07-25 09:25:15.455] [warn] [Motrix] Logger init
[2019-07-25 09:25:15.694] [warn] openedAtLogin===> true
[2019-07-25 15:14:26.777] [warn] [Motrix] Logger init
[2019-07-25 15:14:27.020] [warn] openedAtLogin===> true
[2019-07-26 19:59:04.967] [warn] [Motrix] Logger init
[2019-07-26 19:59:05.211] [warn] openedAtLogin===> true
[2019-07-26 20:04:25.892] [warn] [Motrix] Logger init
[2019-07-26 20:04:26.138] [warn] openedAtLogin===> true
[2019-07-26 20:12:13.341] [warn] [Motrix] Logger init
[2019-07-26 20:12:13.594] [warn] openedAtLogin===> true
[2019-07-29 09:18:32.760] [warn] [Motrix] Logger init
[2019-07-29 09:18:32.992] [warn] openedAtLogin===> true
[2019-07-30 16:42:45.897] [warn] [Motrix] Logger init
[2019-07-30 16:42:46.149] [warn] openedAtLogin===> true
[2019-07-30 19:08:32.609] [warn] [Motrix] Logger init
[2019-07-30 19:08:32.926] [warn] openedAtLogin===> true
[2019-08-01 09:07:45.108] [warn] [Motrix] Logger init
[2019-08-01 09:07:45.340] [warn] openedAtLogin===> true
[2019-08-01 09:08:07.227] [error] Error: Error: net::ERR_CONNECTION_TIMED_OUT
    at GenericProvider.getLatestVersion (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:346:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:335:43)
    at C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:362:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:359:34)
    at NsisUpdater.checkForUpdates (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at t.value (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:153193)
    at new t (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:152562)
    at t.value (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:170758)
    at t.value (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:166910)
    at new t (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:166300)
    at App.<anonymous> (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:177132)
    at App.emit (events.js:187:15)
[2019-08-01 09:08:07.236] [warn] [Motrix] update-error: Cannot check for updates: Error: net::ERR_CONNECTION_TIMED_OUT
    at GenericProvider.getLatestVersion (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:346:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:335:43)
    at C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:362:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:359:34)
    at NsisUpdater.checkForUpdates (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at t.value (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:153193)
    at new t (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:152562)
    at t.value (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:170758)
    at t.value (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:166910)
    at new t (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:166300)
    at App.<anonymous> (C:\Users\tpob\AppData\Local\Programs\Motrix\resources\app.asar\dist\electron\main.js:1:177132)
    at App.emit (events.js:187:15)
[2019-08-01 09:18:41.245] [warn] [Motrix] Logger init
[2019-08-01 09:18:41.470] [warn] openedAtLogin===> true
[2019-08-04 12:46:10.631] [warn] [Motrix] Logger init
[2019-08-04 12:46:10.853] [warn] openedAtLogin===> true
[2019-08-04 15:32:42.465] [warn] [Motrix] Logger init
[2019-08-04 15:32:42.723] [warn] openedAtLogin===> true
[2019-08-05 09:18:59.672] [warn] [Motrix] Logger init
[2019-08-05 09:18:59.911] [warn] openedAtLogin===> true
[2019-08-05 13:19:50.740] [warn] [Motrix] Logger init
[2019-08-05 13:19:51.011] [warn] openedAtLogin===> true
[2019-08-05 13:28:30.119] [warn] [Motrix] Logger init
[2019-08-05 13:28:30.363] [warn] openedAtLogin===> true
[2019-08-06 08:57:40.501] [warn] [Motrix] Logger init
[2019-08-06 08:57:40.802] [warn] openedAtLogin===> true
[2019-08-06 15:22:20.905] [warn] [Motrix] Logger init
[2019-08-06 15:22:21.153] [warn] openedAtLogin===> true
[2019-08-06 15:27:07.049] [warn] [Motrix] Logger init
[2019-08-06 15:27:07.284] [warn] openedAtLogin===> true
[2019-08-07 09:15:22.740] [warn] [Motrix] Logger init
[2019-08-07 09:15:22.989] [warn] openedAtLogin===> true
[2019-08-08 09:36:03.596] [warn] [Motrix] Logger init
[2019-08-08 09:36:03.877] [warn] openedAtLogin===> true
[2019-08-10 13:49:47.028] [warn] [Motrix] Logger init
[2019-08-10 13:49:47.264] [warn] openedAtLogin===> true
[2019-08-10 14:47:21.295] [warn] [Motrix] Logger init
[2019-08-10 14:47:21.550] [warn] openedAtLogin===> true
[2019-08-10 18:02:54.341] [warn] [Motrix] Logger init
[2019-08-10 18:02:54.597] [warn] openedAtLogin===> true
[2019-08-10 20:10:27.186] [warn] [Motrix] Logger init
[2019-08-10 20:10:27.418] [warn] openedAtLogin===> true
[2019-08-11 15:04:25.184] [warn] [Motrix] Logger init
[2019-08-11 15:04:25.450] [warn] openedAtLogin===> true
[2019-08-12 09:22:38.725] [warn] [Motrix] Logger init
[2019-08-12 09:22:38.960] [warn] openedAtLogin===> true
[2019-08-12 15:46:53.093] [warn] [Motrix] Logger init
[2019-08-12 15:46:53.352] [warn] openedAtLogin===> true
[2019-08-13 14:09:26.588] [warn] [Motrix] Logger init
[2019-08-13 14:09:26.812] [warn] openedAtLogin===> true
[2019-08-15 16:52:49.108] [warn] [Motrix] Logger init
[2019-08-15 16:52:49.358] [warn] openedAtLogin===> true
[2019-08-16 09:27:25.028] [warn] [Motrix] Logger init
[2019-08-16 09:27:25.273] [warn] openedAtLogin===> true
[2019-08-18 19:00:18.616] [warn] [Motrix] Logger init
[2019-08-18 19:00:18.875] [warn] openedAtLogin===> true
[2019-08-19 09:31:25.907] [warn] [Motrix] Logger init
[2019-08-19 09:31:26.306] [warn] openedAtLogin===> true
[2019-08-19 10:16:42.367] [warn] [Motrix] Logger init
[2019-08-19 10:16:42.658] [warn] openedAtLogin===> true
[2019-08-22 09:32:35.695] [warn] [Motrix] Logger init
[2019-08-22 09:32:36.009] [warn] openedAtLogin===> true
[2019-08-22 20:05:40.242] [warn] [Motrix] Logger init
[2019-08-22 20:05:40.553] [warn] openedAtLogin===> true
[2019-08-23 09:28:32.769] [warn] [Motrix] Logger init
[2019-08-23 09:28:33.001] [warn] openedAtLogin===> true
[2019-08-25 14:37:18.293] [warn] [Motrix] Logger init
[2019-08-25 14:37:18.547] [warn] openedAtLogin===> true
[2019-08-25 20:27:04.292] [warn] [Motrix] Logger init
[2019-08-25 20:27:04.585] [warn] openedAtLogin===> true
[2019-08-26 09:24:40.460] [warn] [Motrix] Logger init
[2019-08-26 09:24:40.715] [warn] openedAtLogin===> true
[2019-08-26 16:14:01.083] [warn] [Motrix] Logger init
[2019-08-26 16:14:01.308] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-08-27 09:30:46.670] [warn] [Motrix] Logger init
[2019-08-27 09:30:46.908] [warn] openedAtLogin===> true
[2019-08-27 11:15:34.387] [warn] [Motrix] Logger init
[2019-08-27 11:15:34.635] [warn] openedAtLogin===> true
[2019-08-28 09:21:26.213] [warn] [Motrix] Logger init
[2019-08-28 09:21:26.459] [warn] openedAtLogin===> true
[2019-08-30 09:35:32.955] [warn] [Motrix] Logger init
[2019-08-30 09:35:33.259] [warn] openedAtLogin===> true
[2019-08-30 21:16:14.580] [warn] [Motrix] Logger init
[2019-08-30 21:16:14.821] [warn] openedAtLogin===> true
[2019-08-30 21:33:57.070] [warn] [Motrix] Logger init
[2019-08-30 21:33:57.338] [warn] openedAtLogin===> true
[2019-08-30 21:36:42.918] [warn] [Motrix] Logger init
[2019-08-30 21:36:43.140] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-08-31 08:30:57.700] [warn] [Motrix] Logger init
[2019-08-31 08:30:57.945] [warn] openedAtLogin===> true
[2019-08-31 10:33:09.895] [warn] [Motrix] Logger init
[2019-08-31 10:33:10.156] [warn] openedAtLogin===> true
[2019-09-01 22:25:10.727] [warn] [Motrix] Logger init
[2019-09-01 22:25:10.979] [warn] openedAtLogin===> true
[2019-09-02 09:32:24.467] [warn] [Motrix] Logger init
[2019-09-02 09:32:24.705] [warn] openedAtLogin===> true
[2019-09-05 10:26:43.620] [warn] [Motrix] Logger init
[2019-09-05 10:26:43.848] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-09-06 10:48:58.513] [warn] [Motrix] Logger init
[2019-09-06 10:48:58.744] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-09-07 11:05:25.840] [warn] [Motrix] Logger init
[2019-09-07 11:05:26.094] [warn] openedAtLogin===> true
[2019-09-07 13:08:41.518] [warn] [Motrix] Logger init
[2019-09-07 13:08:41.743] [warn] openedAtLogin===> false
[2019-09-07 13:10:12.274] [warn] [Motrix] Logger init
[2019-09-07 13:10:12.505] [warn] openedAtLogin===> false
[2019-09-07 13:12:18.474] [warn] [Motrix] Logger init
[2019-09-07 13:12:18.709] [warn] openedAtLogin===> true
[2019-09-07 13:25:09.974] [warn] [Motrix] Logger init
[2019-09-07 13:25:10.263] [warn] openedAtLogin===> false
[2019-09-07 13:25:31.586] [warn] [Motrix] Logger init
[2019-09-07 13:25:31.809] [warn] [Motrix] Logger init
[2019-09-07 13:25:31.878] [warn] openedAtLogin===> true
[2019-09-07 13:25:32.184] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-09-07 13:31:43.946] [warn] [Motrix] Logger init
[2019-09-07 13:31:44.167] [warn] openedAtLogin===> false
[2019-09-07 13:35:23.592] [warn] [Motrix] Logger init
[2019-09-07 13:35:23.819] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-09-07 13:35:48.703] [warn] [Motrix] Logger init
[2019-09-07 13:35:48.924] [warn] openedAtLogin===> false
[2019-09-07 13:38:14.811] [warn] [Motrix] Logger init
[2019-09-07 13:38:15.042] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Temp\\1N3OiVYwScsYRp72X4Cr8TsUIrn\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Temp\1N3OiVYwScsYRp72X4Cr8TsUIrn
[2019-09-07 13:38:25.352] [warn] [Motrix] Logger init
[2019-09-07 13:38:25.579] [warn] openedAtLogin===> false
[2019-09-07 13:39:33.803] [warn] [Motrix] Logger init
[2019-09-07 13:39:44.188] [warn] [Motrix] Logger init
[2019-09-07 13:39:44.394] [warn] second-instance====> { preventDefault: [Function: preventDefault],
  sender:
   App {
     _events:
      { login: [Function],
        'certificate-error': [Function],
        'select-client-certificate': [Function],
        quit: [Function],
        'web-contents-created': [Array],
        'session-created': [Function],
        'will-quit': [Array],
        ready: [Function],
        'second-instance': [Function],
        'open-url': [Function],
        activate: [Function],
        'before-quit': [Function],
        'window-all-closed': [Function] },
     _eventsCount: 13,
     _maxListeners: undefined,
     setApplicationMenu: [Function: setApplicationMenu],
     getApplicationMenu: [Function: getApplicationMenu],
     commandLine:
      { appendSwitch: [Function: appendSwitch],
        appendArgument: [Function: appendArgument] },
     getAppMetrics: [Function],
     isPackaged: true,
     allowNTLMCredentialsForAllDomains: [Function] } } [ 'C:\\Tools\\Programs\\download\\motrix\\Motrix.exe' ] C:\Tools\Programs\download\motrix
[2019-09-07 14:11:43.502] [warn] [Motrix] Logger init
[2019-09-07 14:11:43.737] [warn] openedAtLogin===> true
[2019-09-08 12:27:31.212] [warn] [Motrix] Logger init
[2019-09-08 12:27:31.445] [warn] second-instance====> [ 'C:\\Users\\tpob\\AppData\\Local\\Programs\\Motrix\\Motrix.exe' ] C:\Users\tpob\AppData\Local\Programs\Motrix
[2019-09-08 20:10:20.872] [warn] [Motrix] Logger init
[2019-09-08 20:10:21.104] [warn] openedAtLogin===> true
[2019-09-09 09:31:17.827] [warn] [Motrix] Logger init
[2019-09-09 09:31:18.100] [warn] openedAtLogin===> true
[2019-09-10 15:25:51.205] [warn] [Motrix] Logger init
[2019-09-10 15:25:51.435] [warn] openedAtLogin===> true
[2019-09-10 15:57:31.930] [warn] [Motrix] Logger init
[2019-09-10 15:57:32.172] [warn] openedAtLogin===> true
[2019-09-10 16:04:52.794] [warn] [Motrix] Logger init
[2019-09-10 16:04:53.062] [warn] openedAtLogin===> true
[2019-09-11 09:39:50.372] [warn] [Motrix] Logger init
[2019-09-11 09:39:50.613] [warn] openedAtLogin===> true
[2019-09-12 20:17:26.561] [warn] [Motrix] Logger init
[2019-09-12 20:17:26.808] [warn] openedAtLogin===> true
[2019-09-12 22:44:24.881] [warn] [Motrix] Logger init
[2019-09-12 22:44:25.128] [warn] openedAtLogin===> true
[2019-09-14 21:39:21.726] [warn] [Motrix] Logger init
[2019-09-14 21:39:21.999] [warn] openedAtLogin===> true
[2019-09-15 09:34:34.838] [warn] [Motrix] Logger init
[2019-09-15 09:34:35.092] [warn] openedAtLogin===> false
[2019-09-15 09:35:32.201] [warn] [Motrix] Logger init
[2019-09-15 09:35:32.424] [warn] openedAtLogin===> false



日志未见异常

**Comment by dajibaxiao** [comment]
我win7也是同样问题.重装重启无效

**Comment by agalwood** [comment]
Closing as legacy-v1.

Motrix v2 has replaced the legacy 1.x codebase, so this issue is no longer tracked. If it still reproduces with the latest Motrix v2 beta, please open a new issue with the current Motrix version, OS, reproduction steps, and logs.

Motrix v2 已替换 1.x 旧架构，因此不再跟踪此 issue。若问题仍能在最新 Motrix v2 beta 复现，请重新提交 issue，并附上当前版本、系统、复现步骤和日志。
