### ISSUE TITLE
异常弹窗报告 #2

### ISSUE THREAD

**Issue by finalwhy** [agalwood/Motrix#668]
**错误描述**
新的异常弹窗，警告内容为 **"cb is not a function"** (关闭的时候忘了截图了)，看了日志报告应该是调用SAX接口解析xml的时候出错了。

**环境:**
 - window: [e.g. macOS, Windows, Linux]
 - Version: Windows10 2004
 - Motrix Version: v1.5.13
 - Installation package type: exe

**应用日志**
> [2020-05-26 12:21:27.414] [error] TypeError: cb is not a function
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\index.js:336:7
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\lib\upnp\device.js:61:11
    at Parser.<anonymous> (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:199:18)
    at Parser.emit (events.js:210:5)
    at SAXParser.saxParser.onclosetag (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:183:24)
    at emit (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:211:31)
[2020-05-26 13:13:58.922] [error] [Motrix] Uncaught exception: cb is not a function
[2020-05-26 13:13:58.923] [error] TypeError: cb is not a function
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\index.js:336:7
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\lib\upnp\device.js:61:11
    at Parser.<anonymous> (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:199:18)
    at Parser.emit (events.js:210:5)
    at SAXParser.saxParser.onclosetag (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:183:24)
    at emit (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:211:31)
[2020-05-26 13:13:59.542] [error] [Motrix] Uncaught exception: cb is not a function
[2020-05-26 13:13:59.543] [error] TypeError: cb is not a function
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\index.js:336:7
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\lib\upnp\device.js:61:11
    at Parser.<anonymous> (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:199:18)
    at Parser.emit (events.js:210:5)
    at SAXParser.saxParser.onclosetag (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:183:24)
    at emit (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:211:31)
[2020-05-26 13:13:59.991] [error] [Motrix] Uncaught exception: cb is not a function
[2020-05-26 13:13:59.994] [error] TypeError: cb is not a function
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\index.js:336:7
    at C:\Program Files\Motrix\resources\app.asar\node_modules\nat-api\lib\upnp\device.js:61:11
    at Parser.<anonymous> (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:199:18)
    at Parser.emit (events.js:210:5)
    at SAXParser.saxParser.onclosetag (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:183:24)
    at emit (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Program Files\Motrix\resources\app.asar\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (C:\Program Files\Motrix\resources\app.asar\node_modules\xml2js\lib\xml2js.js:211:31)

**Comment by agalwood** [comment]
你的路由器我不清楚为什么用这个 nat-api 库启用不了 UPnP，你还是把这个功能功能关了，手动路由器映射吧

我测试了两个路由器，Apple Time Capsule「不支持UPnP」 + ASUS Router「支持UPnP」，都没出现你这报错 : |

**Comment by finalwhy** [comment]
哦，好的，看来我该换路由了,是有点老了 : |

**Comment by agalwood** [comment]
你的问题我复现了，需要等1小时50分钟才会出现 : (
上次的修复 nat-api 抛异常时看到它支持 autoUpdate，就启用了它，结果这个功能有 bug

fork 了一份 nat-api，先修复了

```javascript
// TTL is 2 hours (min 20 min)
this.ttl = (opts.ttl) ? Math.max(opts.ttl, 1200) : 7200
```

https://github.com/alxhotel/nat-api/blob/8f78f25d7d5dc2d375efb918661936afeb73c1a4/index.js#L17

```javascript
if (self.autoUpdate) {
  self._upnpIntervals[opts.publicPort + ':' + opts.privatePort + '-' + opts.protocol] = setInterval(
    self._upnpMap.bind(self, opts),
    self._timeout
  )
}
```

https://github.com/alxhotel/nat-api/blob/8f78f25d7d5dc2d375efb918661936afeb73c1a4/index.js#L327

**Comment by finalwhy** [comment]
看到回复了，作者辛苦！
