### ISSUE TITLE
start UPnP mapping fail UPnP port mapping failed

### ISSUE THREAD

**Issue by yidasanqian** [agalwood/Motrix#802]
**错误描述**
打开app提示，日志输出警告：start UPnP mapping fail UPnP port mapping failed

**运行环境**
 - 操作系统类型： macOS
 - 具体版本：macOS 10.15.7
 - Motrix 版本： 1.5.15
 - 安装包类型：brew

**更多信息**
```

[2020-10-25 11:21:06.243] [warn] [Motrix] Logger init
[2020-10-25 11:21:07.566] [warn] [Motrix] UPnPManager map 26701 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:49:18)
    at Request.self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
[2020-10-25 11:21:07.570] [warn] [Motrix] start UPnP mapping fail UPnP port mapping failed
[2020-10-25 11:21:07.603] [warn] [Motrix] UPnPManager map 21301 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:49:18)
    at Request.self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
[2020-10-25 11:21:07.823] [warn] [Motrix] auto sync tracker failed: Client network socket disconnected before secure TLS connection was established

```

**Comment by ditata** [comment]
> **错误描述**
> 打开app提示，日志输出警告：start UPnP mapping fail UPnP port mapping failed
> 
> **运行环境**
> 
> * 操作系统类型： macOS
> * 具体版本：macOS 10.15.7
> * Motrix 版本： 1.5.15
> * 安装包类型：brew
> 
> **更多信息**
> 
> ```
> 
> [2020-10-25 11:21:06.243] [warn] [Motrix] Logger init
> [2020-10-25 11:21:07.566] [warn] [Motrix] UPnPManager map 26701 failed, error:  Error: UPnP port mapping failed
>     at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
>     at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
>     at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:49:18)
>     at Request.self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:210:5)
>     at IncomingMessage.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:299:28)
>     at IncomingMessage.emit (events.js:215:7)
> [2020-10-25 11:21:07.570] [warn] [Motrix] start UPnP mapping fail UPnP port mapping failed
> [2020-10-25 11:21:07.603] [warn] [Motrix] UPnPManager map 21301 failed, error:  Error: UPnP port mapping failed
>     at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
>     at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
>     at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:49:18)
>     at Request.self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:210:5)
>     at IncomingMessage.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:299:28)
>     at IncomingMessage.emit (events.js:215:7)
> [2020-10-25 11:21:07.823] [warn] [Motrix] auto sync tracker failed: Client network socket disconnected before secure TLS connection was established
> ```

在下载 github 资源的时候，有同样的问题

**Comment by zengjiapei3000** [comment]
我也遇到了在win10上，后来打开了上级路由器的upnp功能后，log变成了`[2024-08-19 23:26:10.360] [info]  [Motrix] UPnPManager port 23114 mapping succeeded `

**Comment by agalwood** [comment]
Closing as legacy-v1.

Motrix v2 has replaced the legacy 1.x codebase, so this issue is no longer tracked. If it still reproduces with the latest Motrix v2 beta, please open a new issue with the current Motrix version, OS, reproduction steps, and logs.

Motrix v2 已替换 1.x 旧架构，因此不再跟踪此 issue。若问题仍能在最新 Motrix v2 beta 复现，请重新提交 issue，并附上当前版本、系统、复现步骤和日志。
